name=Arduino Kalman Filter Library
version=1.0.0
author=VOLTS Robotics
maintainer=VOLTS Robtics
sentence=This is going to be a library for the Arduino IDE that allows for easy use of Kalman filter functions.
paragraph=This is a longer description providing more details about the hardware it supports or the problems it solves for when it acutally solves any problems.
category=Sensors
url=https://github.com/VOLTS-Robotics/Arduino_Kalmanfilter_Library
includes=
